---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  spring-deploy
  namespace: spring
spec:
  selector:
    matchLabels:
      app: spring-deploy
  template:
    metadata:
      name: spring-deploy
      labels:
        app: spring-deploy
    spec:
      containers:
        - name: spring-deploy
          image: markmama/spring:12
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: spring
  name: spring-service
spec:
  selector:
      app: spring-deploy
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort