---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Release.Name }}-spring-service
spec:
  selector:
      app: {{ .Chart.Name }}-spring
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort