---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}-node-service
spec:
  selector:
      app: {{ .Chart.Name }}-node-deploy
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
